[package]
name = "week0101"
version = "0.1.0"
authors = ["Lauri Piispanen <lauri.piispanen@reaktor.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "math_benchmark"
harness = false